### ISSUE TITLE
SKOMapEditor - Do not save unseen collision rects

### ISSUE THREAD

**Issue by OptimusPi** [OptimusPi/SKO-Utilities#4]
Do not save collision rects that are < 3px width and <3px height
Do not LOAD collision rects this small, either (that way we can fix bugs in existing maps where this has happened)

**Comment by RaghuC99** [comment]
I added a check inside of the timestep for collision rectangles that meet these requirements (though I found 4px to be a better sweet spot), and I removed these rectangles. They are still /created/, but deleted soon after. I've created a new branch for this.
I could have done a check for the size before they are created, but ATM the boxes are created on a mouse click, and edited on mouse release. Doing the check before the creation would involve refactoring this process.

**Comment by OptimusPi** [comment]
## Make this a function not just a chunk of code thrown somewhere

### When NOT to call this function
* Do not call the function in the main timestep loop

### When to call this function
* Call the function after map load
* Call function before map save
* Call function after placing collision rect


Should be minimal effort on your branch. Make a pull request now so we can compare as you go.
